### PR TITLE
Removing validation on payload

### LINKED ISSUE #30: "text" is not obligatory in messages
Was using the message builder and it says i need to add text before calling `create`, but while using the Slack API i noticed that you can set `text` in the attachment, so this is not necessary.

Any thoughts on this?

### PR DESCRIPTION
**Pull request by rdohms**
As discussed on #30, I removed the validations on text and fallback since the API does not require these in the simple way described here.

This Closes #30.

### CODE REVIEW

**Comment by mcrumm** [comment]
@rdohms Thanks!  I really appreciate your input on this, and you taking the time to submit a PR.  Your point about it not being sensible to attempt to recover from the thrown exception was especially insightful.

If you can drop the [failing empty text spec](https://github.com/mcrumm/phlack/blob/develop/spec/Crummy/Phlack/Builder/MessageBuilderSpec.php#L21) in MessageBuilder, I'd be happy to merge this, and cut a new release.

Thanks, again!

**Comment by rdohms** [comment]
will do, forgot to run phpspec before the rebase

**Comment by rdohms** [comment]
Done.

Thanks for the lib! I noticed you mention in a few issues you were planning to abandon it, whats that looking like now?

**Comment by mcrumm** [comment]
Well, I had planned to abandon it, but people keep downloading it. :-)  I had grand plans to add far more functionality, too, but lately I just haven't had time to work on it.

If the maintenance gets to be too much to handle, I may look at handing the project over to another maintainer, but other than that, I decided I'll keep it around as long as it's relevant.

**Comment by rdohms** [comment]
Awesome, thanks! I'll see if i can send more PRs your way the more I use it.

**Comment by mcrumm** [comment]
Please do!

**Pull request merged**
