### PR TITLE
Remove channel autoprefix

### PR DESCRIPTION
**Pull request by errodr**
1. Removed channel normalizer from Message.php, this normalizer automatically prefixed channels.
2. Removed ternary operation from Message.php, this ternary automatically prefixed channels.
3. Removed one test
4. Added new test

### CODE REVIEW

**Comment by mcrumm** [comment]
Can you update the behat tests, as well?  Take a look at the Travis CI output to see which ones failed.

**Comment by errodr** [comment]
Sure thing. I did not notice those before.

--
  Eric Rodriguez
  eric@ericr.com
 
 
 
On Wed, Nov 4, 2015, at 01:54 PM, Michael Crumm wrote:
> Can you update the behat tests, as well?  Take a look at the Travis CI output to see which ones failed.


> —
> Reply to this email directly or view it on GitHub[1]. 


>  
 


Links:

  1. https://github.com/mcrumm/phlack/pull/25#issuecomment-153880690

**Comment by mcrumm** [comment]
Sweet -- if you could squash those two commits, I'll get this merged.

**Comment by errodr** [comment]
I've messed this up pretty good. I'll submit a new request shortly.

**Pull request closed without merging**
