### PR TITLE
ApiClient: chat messages support

### PR DESCRIPTION
**Pull request by kordero**

### CODE REVIEW

**Comment by kordero** [comment]
hey @mcrumm I'm not sure that the Scrutinizer problem is because of my changes. I just want to let you pull this and merge to master so we can use Phlack to send some chat notifications to Slack channels. 

I was already able to make it work by loading an custom service description from an extra json that we're storing in our project but I'd love to have it more elegant and let this project to have it.

**Comment by kordero** [comment]
Btw I'm adding support to these methods:

https://api.slack.com/methods/chat.delete
https://api.slack.com/methods/chat.postMessage
https://api.slack.com/methods/chat.update

Just let me know if I'm missing something or need to change some stuff from the diff. Thanks!

**Comment by mcrumm** [comment]
The scrutinizer config likely needs updated -- it's not an issue with your commits.

I'm merging this, now.  I'll add some docs and tag a new release, shortly.

Thanks for the PR! :smile:

**Comment by mcrumm** [comment]
@kordero I've tagged a new release that includes your updates.

Thanks, again, for the PR!

**Pull request merged**
